### ISSUE TITLE
SEGV under some cases on Ruby 2.5.1

### ISSUE THREAD

**Issue by SamSaffron** [discourse/mini_racer#90]
I am unsure what the root cause here is but if I run this on Ruby 2.5.1: 

```
 % repeat 100 { bundle exec rake }
```

One in say 20-40 runs will produce: 

```
Received signal 11 SEGV_MAPERR 000000000038

==== C stack trace ===============================

 [0x7f8ae6e65e0e]
 [0x7f8ae6e66800]
 [0x7f8aeb0a3890]
 [0x564936c7350d]
 [0x564936c7ae0f]
 [0x564936c7f5fd]
 [0x564936c8049c]
 [0x564936c80774]
 [0x564936c80860]
 [0x564936c809e2]
 [0x564936c7ae26]
 [0x564936c7f5fd]
 [0x564936c8049c]
 [0x564936c80774]
 [0x564936c80860]
 [0x564936c82807]
 [0x564936c833a1]
 [0x564936c83a6b]
 [0x564936b01c2f]
 [0x7f8ae67e5dda]
 [0x564936c3ef22]
 [0x7f8ae67e5ef2]
 [0x7f8ae6c092ed]
 [0x7f8ae6c442c2]
 [0x7f8ae6c44dac]
 [0x34007170465d]
[end of stack trace]
Segmentation fault (core dumped)
```

We are seeing a few of these in production too. We need to get down to the root cause (bug in v8 or mini racer bug)

**Comment by ignisf** [comment]
I can produce a V8 binary with debugging symbols if necessary.

**Comment by SamSaffron** [comment]
update we have a debug symbol binary at: (thanks to @ignisf )

https://github.com/cowboyd/libv8/releases/download/v6.7.288.46.1beta0/debug-libv8-6.7.288.46.1beta0-x86_64-linux.gem

I corrected an easy issue calling unknown functions but the mechanics of snapshots are fundamentally broken v8 wants an isolate around for warmup and stuff gets weird quick. Easy to repro, just checkout https://github.com/discourse/mini_racer/tree/v8-6.7 install the above gem and run the test suite. 

Since @wk8 has been out for quite a while we do not have someone maintaining this piece. 

So, unless I hear back from @wk8 @seanmakesgames or @aviat in the next 24 hours about someone who wants to bring snapshots back into life I will be removing the support from mini racer, updating the doco and doing a new release without snapshot support. 

FYI @cataphract  I had to fix some minor stuff around function invocation, returning Qnil there is still not ideal but I guess it works. 

Once I comment out snapshots I am unable to get this particular segfault ... the odd thing is we do not use snapshots in Discourse so I am still a bit stumped.

**Comment by SamSaffron** [comment]
@ignisf correction I did manage to get that failure you found, investigating why :)

**Comment by aviat** [comment]
@SamSaffron we are fine with removing snapshots here but:
 - we are worried that the bug is still here and that removing the snapshots only changes the memory layout, and just doesn't trigger the bug anymore.
 - we are using snapshots, so we would have to bump the version number to `0.2`, right?

**Comment by seanmakesgames** [comment]
Am using snapshots--
but also have bigger issues: have not been able to move to 6.3 because of strange memory issues, but have not had time to fully investigate and isolate a repro. Still on 5.9 because i'm doing a major version launch here on thursday. Definitely want to move up in versions, but can't yet.

**Comment by seanmakesgames** [comment]
Also ruby version I'm on is 2.2.4

**Comment by SamSaffron** [comment]
OK I managed to fix this with this very messy commit: https://github.com/discourse/mini_racer/commit/3c6832c07b2c6073e547de79da5badc00041ddad 

I am discussing with the v8 team if the assertion that a snapshot must be created every time you use the API is correct. 

@ignisf the good news is that now our test suite all passes, the bad news is I am about 4-6 hours down and am still unable to fix this nasty segfault. I am enlisting more help 

@seanmakesgames  I sadly explicitly just dropped support for 2.2, as policy I want mini_racer to only support non EOL ruby. @aviat  I am not certain but we may be dealing with 2 different issues here, I will update here as I make progress.

**Comment by SamSaffron** [comment]
OK ... I got some help from a friend here and got this sorted ... so gnarly. It appears to have been a nasty GC issue. 

https://github.com/discourse/mini_racer/commit/6b3b1de35b5fbc172d156005308a1a966bbde678

@ignisf I am good to do a mini_racer release now, can you do a stable version of libv8 so we can bump master?

**Comment by ignisf** [comment]
🎉

I've outlined what's left to do in https://github.com/cowboyd/libv8/pull/258

**Comment by SamSaffron** [comment]
@ignisf some news on the checks that were failing: 

https://groups.google.com/forum/#!topic/v8-dev/jatawFG_lus

It does not impact us too much, but maybe if we ever build debug packages we should patch out the check there? 

I am thinking a nice safe thing to do long term is run travis with a debug libv8 as well so we can catch assertions.
